### ISSUE TITLE
"Computing quotient graph" takes lots of memory

### ISSUE THREAD

**Issue by de11n** [symphorien/nix-du#17]
On a huge `/nix/store` (11 TB) with many, many GC roots, `nix-du` uses hundreds of GB of memory to compute the quotient graph and gets OOMed. Can you recommend any potentially low-hanging fruit for reducing its memory usage? If not possible, would it be possible to give `nix-du` a directory of GC roots to consider instead of considering all of them?

**Comment by symphorien** [comment]
How large are we speaking ? Can you tell precisely:
- the number of gc roots
- the number of nodes/edges as printed by  nix-du before it crashes
- what filters you intend to use, and how many gc-roots you expect to "survive" the filter

The algorithm uses memory linearly in the number of gc roots iirc (I didn't take the time to look again) so if you really mean many gc roots that could explain :)

**Comment by de11n** [comment]
My guess is that it's crashing before it hits the filtering stage because memory climbs at several GiB per second and takes nearly 200 GiB before being killed (the machine has a lot of memory :D). That's also confirmed by the fact that I've specified `-n=50` in hopes that it was the dot generation, but it doesn't help.

There are a lot of roots (this includes transient roots, of course):
```
nix-store --gc --print-roots | wc -l
1551688
```

```
nix-du -O0 -n=50
4325879 nodes, 44421500 edges read.
Size statistics for the whole store:
        Alive: 10.2 TB (not taking optimisation into account)
        Total: 11.6 TB (not taking optimisation into account)
```

**Comment by symphorien** [comment]
thank you for the details. can you try the branch https://github.com/symphorien/nix-du/tree/memory-efficient-algo ? it should reduce the memory consumption from 1 bit per root and node to 128 bits per nodes, which is much more reasonable :)

**Comment by de11n** [comment]
That worked wonders! It took over an hour to finish, but memory consumption was very reasonable the entire time! Nice work!

**Comment by symphorien** [comment]
cool! I released a new version with the fix.

I'm a bit curious, did you extract useful info from the resulting graph, on so large a graph with so many roots?

**Comment by de11n** [comment]
"Interesting" information was probably the best description. Ultimately, we ended up doing a deep dive into Hydra's source to discovery why it was holding so many roots.
