### ISSUE TITLE
Panic 'Unknown store path type: {lsof}'

### ISSUE THREAD

**Issue by lilyball** [symphorien/nix-du#2]
`nix-du` panics on my computer

```
> nix run nixpkgs.nix-du -c nix-du
Reading dependency graph from store... removing stale temporary roots file '/nix/var/nix/temproots/67725'
thread 'main' panicked at 'Unknown store path type: {lsof}', src/depgraph.rs:182:13
stack backtrace:
   0: std::sys_common::backtrace::print
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::continue_panic_fmt
   5: std::panicking::begin_panic_fmt
   6: register_node
   7: _ZNSt3__110__function6__funcIZ13populateGraphE3$_0NS_9allocatorIS2_EEFvvEEclEv
   8: _ZN3nix16handleExceptionsERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS0_8functionIFvvEEE
   9: populateGraph
  10: nix_du::depgraph::DepInfos::read_from_store
  11: nix_du::main
```

---

 - nix-du: `0.3.0`
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3`
 - channels(lily): `"nixpkgs-20.03pre193309.c4196cca9ac"`
 - nixpkgs: `/Users/lily/.nix-defexpr/channels/nixpkgs`

**Comment by symphorien** [comment]
Oops, I forgot to push to another branch. If the fix does not work, feel free to reopen.

**Comment by lilyball** [comment]
Latest master no longer panics. I get a bunch of test failures (filed as [https://github.com/symphorien/nix-du/issues/3]) but they seem to be unrelated to this panic issue.
